wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1658853573
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 24
      4: 3.9.7
      5: 0.12.9
      8:
      - 5
